# Generated by Django 5.2.8 on 2025-11-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
