# Generated by Django 5.2.8 on 2025-11-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_email_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Cancelled', 'Cancelled')], default='Present', max_length=10),
        ),
    ]
